### ISSUE TITLE
Atribuição OpenStreetMap

### ISSUE THREAD

**Issue by CaldeiraG** [afonsosousah/mGira#2]
Boas @afonsosousah, vi a tua aplicação partilhada no Twitter e está aqui um bom esforço para refazer a app da Gira :)

No entanto reparei que quando inicializas o mapa do OpenStreetMap não tens a atribuição necessária para estar em conformidade com os [termos de atribuição e conformidade](https://www.openstreetmap.org/copyright) do OSM. 

É relativamente fácil pelo o que indica a documentação do OpenLayers: https://openlayers.org/en/latest/examples/attributions.html

```js

import {Attribution, defaults as defaultControls} from 'ol/control.js';

const attribution = new Attribution({
  collapsible: false,
});

const map = new Map({
  layers: [
    new TileLayer({
      source: new OSM(),
    }),
  ],
  controls: defaultControls({attribution: true}).extend([attribution]),
});
```

Bom trabalho!

**Comment by afonsosousah** [comment]
corrigido na versão 0.0.2
