### ISSUE TITLE
feat: Possibilidade de Aumentar a Distância à Estação Para Desbloquear Bicicleta

### ISSUE THREAD

**Issue by filipe-maia** [afonsosousah/mGira#23]
Boas.
Infelizmente o GPS do meu telemóvel por vezes não assinala bem a minha localização.
Posso estar mesmo ao lado da bicicleta, mas no mapa estou uns metros afastado e a app não me deixa retirar a bicicleta.
É costume ter de me afastar da estação, de modo a que a minha localização no mapa fique na estação, para conseguir desbloquear a bicicleta, o que gera mal entendidos com outras pessoas que chegam lá entretanto e que pensam que a bicicleta está livre.
Sugeria maneira de definir nas opções a distância mínima antes de dar erro (por exemplo: 10metros, 15metros, etc.) ou sugeria que a app desse um erro estilo "O seu GPS indica que está demasiado afastado desta estação, deseja mesmo assim desbloquear esta bicicleta?".
Obrigado.

**Comment by afonsosousah** [comment]
Olá!

Desde já agradeço a sugestão. A opção de dar o erro mesmo estando afastado da bicicleta, não me parece muito boa, mas a possibilidade de poder mudar a distância necessária até à estação parece-me razoável.

Teria alguma sugestão para as opções das distâncias? A distância atual definida na aplicação é de 50 metros.

Obrigado!

**Comment by filipe-maia** [comment]
Olá.

Pensei que a distância actual definida na aplicação era menos que 50 metros, o GPS do meu telemóvel não deve ser grande coisa :P

Talvez 50metros, 75metros e 100metros. Não sei se há mais sugestões

Obrigado.

**Comment by afonsosousah** [comment]
Obrigado, vou anotar para ser adicionado em versões futuras!

**Comment by afonsosousah** [comment]
@filipe-maia se quiseres testar a opção de mudar a distância mínima para a estação, podes ir a https://alpha.mgira.pt
