### ISSUE TITLE
mGira Não funciona no Chrome Android

### ISSUE THREAD

**Issue by DXBOSS12** [afonsosousah/mGira#27]
Quando tento usar a mGira no meu telemovel Android através do Chrome, tanto no website como na aplicação (instalada a partir da app.mgira.pt), nada funciona. Quando uso o Firefox Android tudo funciona bem. Eu tenho o Samsung Galaxy A22 5G com o Android 13.

Isto é o que aparece quando uso a app.mgira.pt, é quando carrego no botão de ver as bicicletas numa estação qualquer (os icons aparecem gigantes):
![website2](https://github.com/afonsosousah/mGira/assets/156956886/df620091-d307-4511-b8e1-0abd25c709fa)

E Isto é o que aparece com o website instalado, a 1ª foto é quando carrego no botão com as informações do utilizador:
![app1](https://github.com/afonsosousah/mGira/assets/156956886/1047da5a-1e27-4a79-8585-6183218384b7)
![app2](https://github.com/afonsosousah/mGira/assets/156956886/f1824100-4d3e-43ae-8d12-fa1a0b1bffb4)

**Comment by afonsosousah** [comment]
Olá!

Utilizaste previamente a mGira no chrome? Pode estar a acontecer porque a cache não atualizou. Experimenta ir a Definições -> Apps -> Chrome -> Armazenamento -> Limpar cache
