### ISSUE TITLE
Estimativas de poupança de CO2eq

### ISSUE THREAD

**Issue by temospena** [afonsosousah/mGira#3]
Viva,
Parabéns pela iniciativa!

Venho só sugerir uma alteração.
As estimativa de 250g/km está um pouco sobredimensionada.
Provavelmente porque assume que as viagens em GIRA vêm substituir viagens em automóvel, o que não é o caso em 100% das vezes.

Num estudo realizado pelo IST para a EMEL sobre as estimativas dos impactes socioeconómicos da GIRA, com base nos dados de viagens de 2018, e com base em inquérito complementar com mais de 3mil respostas, estimámos que:
> "Esta poupança representa, em média, uma redução de 120g CO2eq por cada viagem realizada numa GIRA (o que varia necessariamente com a distância da viagem e o modo que vem substituir). Por km percorrido, o fator médio de emissão poupada foi **54g CO2eq/km**."

Resumo dos resultados do estudo aqui: http://ushift.tecnico.ulisboa.pt/estudo-de-impactes-socio-economicos-da-gira-na-national-geographic/

**Comment by afonsosousah** [comment]
Muito obrigado por partilhares esta informção! Apenas me guiei pelos resultados que encontrei inicialmente, não fazia ideia que realmente houve um estudo específico para a Gira! Tratarei disso para a próxima release!

**Comment by afonsosousah** [comment]
corrigido na versão 0.0.2
