### ISSUE TITLE
App not showing stations

### ISSUE THREAD

**Issue by ricardoomoreira** [afonsosousah/mGira#51]

**Comment by ricardoomoreira** [comment]
@afonsosousah

**Comment by Lucasgrimault** [comment]
![Screenshot_2024-11-08-19-16-48-447_com android chrome](https://github.com/user-attachments/assets/30399c43-8a9f-49f7-9a37-34f31c69eaa4)
O mesmo problema

**Comment by cyberastr4l** [comment]
Hello, the stations stopped showing because EMEL changed their APIs, they warned about this change in May. For more info you can check ou this issue on Gira+ repo: https://github.com/rt-evil-inc/gira/issues/22

Olá, as estações deixaram de mostrar porque a EMEL mudou os APIs, eles avisaram disto em Maio. Para mais info vê esta issue no repo da app Gira+: https://github.com/rt-evil-inc/gira/issues/22

**Comment by Lucasgrimault** [comment]
Mas deixamos de conseguir usar a mGira então?

**Comment by afonsosousah** [comment]
Boa noite,
Estamos a trabalhar para resolver a situação!
Obrigado

**Comment by cyberastr4l** [comment]
@afonsosousah Os da Gira+ já resolveram, poderias falar ou ver o que eles fizeram e tentar implementar na tua App.

**Comment by cyberastr4l** [comment]
@afonsosousah Acabei de checkar o alpha.mgira.pt e mostra as estações e tal mas quando carrego numa estação fica em loading inifinito e não mostra as bicicletas disponiveis. Sei que ainda estás a trabalhar nisso que eu vi nas actions, apenas um heads up. Quando achas que está totalmente funcional para uso, no alpha.mgira.pt ou no app.mgira.pt?

**Comment by afonsosousah** [comment]
> @afonsosousah Os da Gira+ já resolveram, poderias falar ou ver o que eles fizeram e tentar implementar na tua App.
 
Obrigado! Eles ajudaram-me a resolver os problemas


> @afonsosousah Acabei de checkar o alpha.mgira.pt e mostra as estações e tal mas quando carrego numa estação fica em loading inifinito e não mostra as bicicletas disponiveis. Sei que ainda estás a trabalhar nisso que eu vi nas actions, apenas um heads up. Quando achas que está totalmente funcional para uso, no alpha.mgira.pt ou no app.mgira.pt?

Supostamente no alpha.mgira.pt está a funcionar totalmente. Se acontecer novamente isso, podes mostrar-me o log da consola?

**Comment by cyberastr4l** [comment]
Voltei a ir ao website e voltou a acontecer. Ao entrar no site aparece o erro da primeira screenshot: 
![Screenshot from 2024-11-09 22-46-01](https://github.com/user-attachments/assets/7ff60fce-03c9-457c-99f5-f7067f3f8316)
E após selecionar uma estação e ficar no loading infinito aparece um segundo erro: 
![Screenshot from 2024-11-09 22-46-30](https://github.com/user-attachments/assets/39ebafbc-a79c-4ce5-851d-4d280f66ce3c)
Acima usei o Firefox, nas duas abaixo exatamente o mesmo behavior e usei o Chromium:
![Screenshot from 2024-11-09 22-50-24](https://github.com/user-attachments/assets/b0692420-74bd-4b22-84de-912a664587b1)
![Screenshot from 2024-11-09 22-50-31](https://github.com/user-attachments/assets/c31fd7dd-5471-4e7b-939c-cfe7481fc286)

**Comment by cyberastr4l** [comment]
Acabei de voltar a abrir, desta vez aceitei a permissão de localização e funcionou, voltei a testar sem a permissão e não funcionava. Não sei o porque de estar dependente da localização mas parece me estár a funcionar bem. Se encontrar mais alguma coisa avisarei. Esses erros acima são apenas de não ter dado a permissão ou são de outra coisa tambem? 
Já agora, quando será lançado na app.mgira.pt?

**Comment by afonsosousah** [comment]
> Acabei de voltar a abrir, desta vez aceitei a permissão de localização e funcionou, voltei a testar sem a permissão e não funcionava. Não sei o porque de estar dependente da localização mas parece me estar a funcionar bem. Se encontrar mais alguma coisa avisarei. Esses erros acima são apenas de não ter dado a permissão ou são de outra coisa tambem? Mesmo já estando a funcionar ainda há erros na consola. Já agora, quando será lançado na app.mgira.pt?

Obrigado! O erro que está a acontecer é que para mostrar a distância para a estação num quadradinho é preciso a localização.
Espero que hoje ou amanhã saia para a app.mgira.pt

**Comment by afonsosousah** [comment]
Já saiu a nova release!
