### ISSUE TITLE
A proxy está atualizada?

### ISSUE THREAD

**Issue by franciscobmacedo** [afonsosousah/mGira#56]
Parece-me que o script da proxy não está atualizado. Por exemplo, `$valid_requests` não inclui os novos urls como "https://egira-proxy-arqetk5clq-ew.a.run.app/api/graphql".

Será que podes atualizar este script? Tanto por razões de transparência mas também porque quero aceder aos dados da Gira fora do contexto da aplicação e está a dar erros de autenticação 😢. Gostava de saber como estás a lidar com isto, se há algum header especifico?

**Comment by afonsosousah** [comment]
Olá!
O script de facto não está atualizado por razões de segurança para a API da EMEL. Não sei se posso partilhar a solução, mas podes entrar em contacto comigo diretamente via email: afonsosousah@hotmail.com

Obrigado!
