### ISSUE TITLE
Botão Android Voltar a atrás sai da aplicação

### ISSUE THREAD

**Issue by DanielAgostinho** [afonsosousah/mGira#6]
O botão "Voltar a atrás" presente na maioria dos androids faz sair da aplicação, algo que deveria ser substituido para ir ao menu anterior(à exceção da pagina inicial da App).

Android Version: 12
mgira Version: V.0.0.2

**Comment by afonsosousah** [comment]
Boa noite,

Será resolvido na próxima atualização!

Obrigado pelo feedback!
