### ISSUE TITLE
Valores de Bónus e Saldo não concordantes

### ISSUE THREAD

**Issue by jhrebordao** [afonsosousah/mGira#7]
Ver imagens em anexo

![Imagem WhatsApp 2023-12-12 às 15 12 07_55a88c28](https://github.com/afonsosousah/mGira/assets/74410509/07c13d31-58b8-4f28-87ad-94c07e9c5efe)
![Imagem WhatsApp 2023-12-12 às 15 11 28_a503930c](https://github.com/afonsosousah/mGira/assets/74410509/4d7b4772-a31c-44fb-b0b6-cc4ee59d5c16)

**Comment by afonsosousah** [comment]
Boa noite!

Sempre que abre o menu do utilizador, aparecem esses valores?
Creio que o erro esteja do lado da API, e por alguma razão está a dar esses valores errados.

Obrigado pelo feedback!

**Comment by jhrebordao** [comment]
Sim, O bónus aparece sempre a null.

**Comment by afonsosousah** [comment]
E o valor do saldo aparece também sempre errado?
É de facto bastante estranho os valores na app da EMEL estarem corretos e na mGira não, já que vão buscar as informações à mesma API

**Comment by jhrebordao** [comment]
Eu não tenho andado de Gira, mas sim na minha conta aparece sempre isto. Na conta da minha filha aparece tudo bem.

**Comment by afonsosousah** [comment]
Acho que infelizmente não consigo corrigir isso

Presume que o erro esteja do lado deles
